### ISSUE TITLE
Add node-tap support

### ISSUE THREAD

**Issue by polotek** [polotek/procstreams#13]
https://github.com/substack/node-tap

**Comment by ghost** [comment]
Actually this: https://github.com/isaacs/node-tap

**Comment by polotek** [comment]
@substack ah, didn't even notice. Thanks. What are the current benefits of tap support anyway?

**Comment by ghost** [comment]
Modules with test suites that support tap output will make it easier to build a cpants for node. But more than that, the node-tap api is excellent for general-purpose testing.

**Comment by polotek** [comment]
This is done. It's not the most well organized. The fact you have to put messages in almost every assert is a bit weird. Also I have other test output interspersed in the tap output. Will that be a problem?
