### ISSUE TITLE
.data() does not work with out pipe

### ISSUE THREAD

**Issue by ghost** [polotek/procstreams#14]
I have to do

`$p('find public').pipe('cat').data`

because

`$p('find public').data`

does not work

v.0.2.0 from a npm install

**Comment by polotek** [comment]
Hmm, can you submit a failing test for this?

**Comment by polotek** [comment]
I can't reproduce this on master. Please reopen with a failing test if it still happens for you.

**Comment by ghost** [comment]
This was a fait while ago.

I will revisit the code it is in; update and see if it is still a problem.

Great library by the way. It has the right spirit.
